name: Sync issue/PR labels

on:
  push:
    branches:
      - "*"

    paths:
      - .github/labels.yml

  workflow_dispatch:

jobs:
  sync:
    name: Sync labels
    runs-on: ubuntu-latest
    if: github.repository_owner == 'luisferlcc'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync with GitHub Labeler
        uses: crazy-max/ghaction-github-labeler@v5

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
